global using OnlineShop.Data.Entities;
global using OnlineShop.Data.Interface;
global using Microsoft.EntityFrameworkCore;
global using OnlineShop.Data;
global using OnlineShop.Data.Repository;
global using OnlineShop.BLL.Common;
global using OnlineShop.BLL.DTOs.CategoryDTOs;
global using OnlineShop.BLL.Interfaces;
global using OnlineShop.BLL.Services;
